server:
  port: 4000
spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/store??useUnicode=true&characterEncoding=utf8&useSSL=false

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:6006/eureka/

zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: true

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
        timeout:
          enabled: false
