server:
  port: 8003
spring:
  application:
    name: sale-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/store??useUnicode=true&characterEncoding=utf8&useSSL=false

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:6006/eureka/

logging:
  level:
    com.sunchs.store.db.business.mapper: DEBUG